export const ROLE_CATEGORIES = {
  burc: {
    title: "♈ Burç Rolü Seç",
    description: "Aşağıdaki menüden burcunu seçerek ilgili rolü alabilirsin.\nBir burç rolün varsa önce kaldırılır, ardından yenisi verilir.",
    color: 0x9b59b6 as number,
    placeholder: "Burcunu seç...",
    roles: [
      { label: "♈ Koç", value: "Koç", emoji: "♈" },
      { label: "♉ Boğa", value: "Boğa", emoji: "♉" },
      { label: "♊ İkizler", value: "İkizler", emoji: "♊" },
      { label: "♋ Yengeç", value: "Yengeç", emoji: "♋" },
      { label: "♌ Aslan", value: "Aslan", emoji: "♌" },
      { label: "♍ Başak", value: "Başak", emoji: "♍" },
      { label: "♎ Terazi", value: "Terazi", emoji: "♎" },
      { label: "♏ Akrep", value: "Akrep", emoji: "♏" },
      { label: "♐ Yay", value: "Yay", emoji: "♐" },
      { label: "♑ Oğlak", value: "Oğlak", emoji: "♑" },
      { label: "♒ Kova", value: "Kova", emoji: "♒" },
      { label: "♓ Balık", value: "Balık", emoji: "♓" },
    ],
  },
  iliski: {
    title: "💞 İlişki Durumu Rolü Seç",
    description: "Aşağıdaki menüden ilişki durumunu seçerek ilgili rolü alabilirsin.\nMevcut ilişki rolün varsa önce kaldırılır.",
    color: 0xe91e63 as number,
    placeholder: "İlişki durumunu seç...",
    roles: [
      { label: "💔 İlişkim Yok", value: "İlişkim Yok", emoji: "💔" },
      { label: "❤️ İlişkim Var", value: "İlişkim Var", emoji: "❤️" },
      { label: "🚫 İlişki Yapmaktan Hoşlanmıyorum", value: "İlişki Yapmaktan Hoşlanmıyorum", emoji: "🚫" },
    ],
  },
  takim: {
    title: "⚽ Takım Rolü Seç",
    description: "Aşağıdaki menüden tuttuğun takımı seçerek ilgili rolü alabilirsin.\nMevcut takım rolün varsa önce kaldırılır.",
    color: 0x27ae60 as number,
    placeholder: "Takımını seç...",
    roles: [
      { label: "🟤 Trabzonspor", value: "Trabzonspor", emoji: "🟤" },
      { label: "💛 Fenerbahçe", value: "Fenerbahçe", emoji: "💛" },
      { label: "⚫ Beşiktaş", value: "Beşiktaş", emoji: "⚫" },
      { label: "🔴 Galatasaray", value: "Galatasaray", emoji: "🔴" },
    ],
  },
  renk: {
    title: "🎨 Renk Rolü Seç",
    description: "Aşağıdaki menüden renk rolünü seçebilirsin.\nMevcut renk rolün varsa önce kaldırılır.",
    color: 0x3498db as number,
    placeholder: "Rengini seç...",
    roles: [
      { label: "⚪ Beyaz", value: "Beyaz", emoji: "⚪" },
      { label: "🩶 Siyah füme", value: "Siyah füme", emoji: "🩶" },
      { label: "🟢 Koyu Yeşil", value: "Koyu Yeşil", emoji: "🟢" },
      { label: "🔴 Koyu Kırmızı", value: "Koyu Kırmızı", emoji: "🔴" },
      { label: "🔵 Koyu Mavi", value: "Koyu Mavi", emoji: "🔵" },
      { label: "💚 Açık Yeşil", value: "Açık Yeşil", emoji: "💚" },
      { label: "💙 Açık Mavi", value: "Açık Mavi", emoji: "💙" },
      { label: "🩵 Turkuaz", value: "Turkuaz", emoji: "🩵" },
      { label: "🩷 Pembe", value: "Pembe", emoji: "🩷" },
      { label: "💜 Mor", value: "Mor", emoji: "💜" },
      { label: "🟠 Turuncu", value: "Turuncu", emoji: "🟠" },
      { label: "💚 Yeşil", value: "Yeşil", emoji: "💚" },
      { label: "❤️ Kırmızı", value: "Kırmızı", emoji: "❤️" },
      { label: "💛 Sarı", value: "Sarı", emoji: "💛" },
      { label: "💙 Mavi", value: "Mavi", emoji: "💙" },
    ],
  },
  katilim: {
    title: "🎟️ Katılım Rolü Seç",
    description: "Aşağıdan katılım türünü seçerek ilgili rolü alabilirsin.\nRolü tekrar seçersen kaldırılır.",
    color: 0xf39c12 as number,
    placeholder: "Katılım rolünü seç...",
    roles: [
      { label: "📺 D/C Katılımcısı", value: "D/C Katılımcısı", emoji: "📺" },
      { label: "🎉 Çekiliş Katılımcısı", value: "Çekiliş Katılımcısı", emoji: "🎉" },
      { label: "🎊 Etkinlik Katılımcısı", value: "Etkinlik Katılımcısı", emoji: "🎊" },
    ],
  },
} as const;

export type CategoryKey = keyof typeof ROLE_CATEGORIES;
